# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-alpine

# set working directory
WORKDIR /app

# Install build dependencies
RUN apk add --no-cache gcc musl-dev linux-headers

# Copy project files
COPY . /app

# Install pip dependencies
RUN pip install --upgrade pip && \
    pip install .

# Expose port if necessary (not specified)

# Start the MCP server
CMD ["python", "kubernetes.py"]
